# Input configuration
input: "/Users/mitch/Documents/GitHub/cityseg/example_inputs"
output_dir: "/Users/mitch/Documents/GitHub/cityseg/example_inputs/output"
#output_prefix: "segmentation_result"
ignore_files: null  # Optional: list of file names to ignore

# Model configuration
model:
  # name: "facebook/mask2former-swin-large-mapillary-vistas-semantic"
  name: "nickmuchi/segformer-b4-finetuned-segments-sidewalk"
  model_type: "segformer"  # Optional: can be 'beit', 'mask2former', or null for auto-detection
  max_size: null  # Optional: maximum size for input images/frames
  device: "mps"  # Options: "cuda", "cpu", "mps", or null for auto-detection
  dataset: "semantic-sidewalk"  # Optional: dataset name for model-specific postprocessing

# Processing configuration
frame_step: 15  # Process every 5th frame
batch_size: 1  # Number of frames to process in each batch
output_fps: null  # Optional: FPS for output video (if different from input)

# Output options
save_raw_segmentation: true
save_colored_segmentation: true
save_overlay: true
analyze_results: true

# Visualization configuration
visualization:
  alpha: 0.5  # Opacity of the segmentation overlay
  colormap: "default"  # Colormap for segmentation visualization

# Advanced options
force_reprocess: false  # Set to true to reprocess even if output files exist
disable_tqdm: true  # Set to true to disable progress bars. In some cases, tqdm seems to lead to segfaults.