input: example_inputs
#output_dir: output
model:
  type: oneformer
  name: shi-labs/oneformer_ade20k_swin_large
  dataset: ade20k
  max_size: null  # Set to null to maintain original resolution
  tile_size: null  # Set to null to disable tiling
  mixed_precision: true
frame_step: 10  # Process every 5th frame
generate_overlay: true
save_colored_segmentation: true
save_raw_segmentation: true
visualization:
  alpha: 0.5
  colormap: default