input: example_inputs
#output_dir: output
model:
  type: oneformer
  name: shi-labs/oneformer_ade20k_swin_large
  dataset: ade20k
  max_size: null  # Set to null to maintain original resolution
  tile_size: null  # Set to null to disable tiling
  mixed_precision: true
  device: mps
frame_step: 50  # Process every 5th frame
save_raw_segmentation: true
save_colored_segmentation: false
save_overlay: true
visualization:
  alpha: 0.5
  colormap: default